// <auto-generated />
using System;
using Audiomusica.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Audiomusica.Infrastructure.Migrations
{
    [DbContext(typeof(AssetManagementDbContext))]
    partial class AssetManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Audiomusica.Domain.Entities.ActivoFijo", b =>
                {
                    b.Property<int>("IdActivoFijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActivoFijo"));

                    b.Property<string>("Detalles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsAF")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDimension")
                        .HasColumnType("int");

                    b.Property<int?>("IdDiscoDuro")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdModelo")
                        .HasColumnType("int");

                    b.Property<int?>("IdProcesador")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("RAM")
                        .HasColumnType("int");

                    b.Property<string>("RutProveedor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdActivoFijo");

                    b.HasIndex("IdDimension");

                    b.HasIndex("IdDiscoDuro");

                    b.HasIndex("IdEstadoActivo");

                    b.HasIndex("IdMarca");

                    b.HasIndex("IdModelo");

                    b.HasIndex("IdProcesador");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("Serial")
                        .IsUnique();

                    b.ToTable("ActivoFijo", (string)null);
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Checklist", b =>
                {
                    b.Property<int>("IdChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChecklist"));

                    b.Property<string>("ExtensionArchivo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("NombreChecklist")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoChecklist")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdChecklist");

                    b.ToTable("Checklist", (string)null);

                    b.HasData(
                        new
                        {
                            IdChecklist = 1,
                            ExtensionArchivo = ".txt",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreArchivo = "checklist-entrega-administrativos.txt",
                            NombreChecklist = "Checklist Entrega Administrativos",
                            RutaArchivo = "Storage/Checklists/checklist-entrega-administrativos.txt",
                            TipoChecklist = "Entrega"
                        },
                        new
                        {
                            IdChecklist = 2,
                            ExtensionArchivo = ".txt",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreArchivo = "checklist-devolucion-equipo.txt",
                            NombreChecklist = "Checklist Devolucion Equipo",
                            RutaArchivo = "Storage/Checklists/checklist-devolucion-equipo.txt",
                            TipoChecklist = "Devolucion"
                        },
                        new
                        {
                            IdChecklist = 3,
                            ExtensionArchivo = ".txt",
                            FechaCreacion = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreArchivo = "checklist-toma-activo-fijo.txt",
                            NombreChecklist = "Checklist Toma Activo Fijo",
                            RutaArchivo = "Storage/Checklists/checklist-toma-activo-fijo.txt",
                            TipoChecklist = "Toma"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCuenta"));

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdCuenta");

                    b.HasIndex("NombreCuenta")
                        .IsUnique();

                    b.ToTable("Cuentas", (string)null);

                    b.HasData(
                        new
                        {
                            IdCuenta = 1,
                            NombreCuenta = "Office"
                        },
                        new
                        {
                            IdCuenta = 2,
                            NombreCuenta = "Microsoft"
                        },
                        new
                        {
                            IdCuenta = 3,
                            NombreCuenta = "Adobe"
                        },
                        new
                        {
                            IdCuenta = 4,
                            NombreCuenta = "SAP"
                        },
                        new
                        {
                            IdCuenta = 5,
                            NombreCuenta = "TPV"
                        },
                        new
                        {
                            IdCuenta = 6,
                            NombreCuenta = "Google (Correo)"
                        },
                        new
                        {
                            IdCuenta = 7,
                            NombreCuenta = "Apple ID"
                        },
                        new
                        {
                            IdCuenta = 8,
                            NombreCuenta = "AutoCAD"
                        },
                        new
                        {
                            IdCuenta = 9,
                            NombreCuenta = "Active Directory"
                        },
                        new
                        {
                            IdCuenta = 10,
                            NombreCuenta = "VPN"
                        },
                        new
                        {
                            IdCuenta = 11,
                            NombreCuenta = "Retail Pro"
                        },
                        new
                        {
                            IdCuenta = 12,
                            NombreCuenta = "Fecele"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Dimension", b =>
                {
                    b.Property<int>("IdDimension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDimension"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreDimension")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroDimension")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdDimension");

                    b.HasIndex("NumeroDimension")
                        .IsUnique();

                    b.ToTable("Dimensiones", (string)null);
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.DiscoDuro", b =>
                {
                    b.Property<int>("IdDiscoDuro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscoDuro"));

                    b.Property<int>("CapacidadGB")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("TipoDisco")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdDiscoDuro");

                    b.ToTable("DiscosDuros", (string)null);

                    b.HasData(
                        new
                        {
                            IdDiscoDuro = 1,
                            CapacidadGB = 256,
                            Descripcion = "SSD 256GB",
                            TipoDisco = "SSD"
                        },
                        new
                        {
                            IdDiscoDuro = 2,
                            CapacidadGB = 512,
                            Descripcion = "SSD 512GB",
                            TipoDisco = "SSD"
                        },
                        new
                        {
                            IdDiscoDuro = 3,
                            CapacidadGB = 1024,
                            Descripcion = "SSD 1TB",
                            TipoDisco = "SSD"
                        },
                        new
                        {
                            IdDiscoDuro = 4,
                            CapacidadGB = 1024,
                            Descripcion = "HDD 1TB",
                            TipoDisco = "HDD"
                        },
                        new
                        {
                            IdDiscoDuro = 5,
                            CapacidadGB = 512,
                            Descripcion = "NVMe 512GB",
                            TipoDisco = "NVMe"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.EstadoActivo", b =>
                {
                    b.Property<int>("IdEstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoActivo"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEstadoActivo");

                    b.ToTable("EstadosActivo", (string)null);

                    b.HasData(
                        new
                        {
                            IdEstadoActivo = 1,
                            NombreEstado = "Disponible"
                        },
                        new
                        {
                            IdEstadoActivo = 2,
                            NombreEstado = "Asignado"
                        },
                        new
                        {
                            IdEstadoActivo = 3,
                            NombreEstado = "En reparacion"
                        },
                        new
                        {
                            IdEstadoActivo = 4,
                            NombreEstado = "Dado de baja"
                        },
                        new
                        {
                            IdEstadoActivo = 5,
                            NombreEstado = "Perdido"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Herramienta", b =>
                {
                    b.Property<int>("IdHerramienta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHerramienta"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDimension")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreHerramienta")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Serial")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TipoHerramienta")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdHerramienta");

                    b.HasIndex("IdDimension");

                    b.ToTable("Herramientas", (string)null);

                    b.HasData(
                        new
                        {
                            IdHerramienta = 1,
                            Activo = true,
                            Cantidad = 3,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreHerramienta = "Martillo",
                            TipoHerramienta = "Manual"
                        },
                        new
                        {
                            IdHerramienta = 2,
                            Activo = true,
                            Cantidad = 1,
                            Estado = "Disponible",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Marca = "Bosch",
                            NombreHerramienta = "Taladro",
                            TipoHerramienta = "Electrica"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdMarca");

                    b.ToTable("Marcas", (string)null);

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            NombreMarca = "HP"
                        },
                        new
                        {
                            IdMarca = 2,
                            NombreMarca = "Lenovo"
                        },
                        new
                        {
                            IdMarca = 3,
                            NombreMarca = "Dell"
                        },
                        new
                        {
                            IdMarca = 4,
                            NombreMarca = "Apple"
                        },
                        new
                        {
                            IdMarca = 5,
                            NombreMarca = "Ubiquiti"
                        },
                        new
                        {
                            IdMarca = 6,
                            NombreMarca = "Brother"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdModelo");

                    b.HasIndex("IdMarca");

                    b.ToTable("Modelos", (string)null);

                    b.HasData(
                        new
                        {
                            IdModelo = 1,
                            IdMarca = 1,
                            NombreModelo = "ProBook 440"
                        },
                        new
                        {
                            IdModelo = 2,
                            IdMarca = 2,
                            NombreModelo = "ThinkPad"
                        },
                        new
                        {
                            IdModelo = 3,
                            IdMarca = 3,
                            NombreModelo = "Latitude"
                        },
                        new
                        {
                            IdModelo = 4,
                            IdMarca = 4,
                            NombreModelo = "MacBook Pro"
                        },
                        new
                        {
                            IdModelo = 5,
                            IdMarca = 4,
                            NombreModelo = "iMac"
                        },
                        new
                        {
                            IdModelo = 6,
                            IdMarca = 5,
                            NombreModelo = "UniFi AP"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.MovimientoActivoFijo", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActivoFijo")
                        .HasColumnType("int");

                    b.Property<int?>("IdDimensionAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("IdDimensionNueva")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioNuevo")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdActivoFijo");

                    b.ToTable("MovimientosActivoFijo", (string)null);
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Procesador", b =>
                {
                    b.Property<int>("IdProcesador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProcesador"));

                    b.Property<string>("NombreProcesador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdProcesador");

                    b.ToTable("Procesadores", (string)null);

                    b.HasData(
                        new
                        {
                            IdProcesador = 1,
                            NombreProcesador = "Intel Core i5"
                        },
                        new
                        {
                            IdProcesador = 2,
                            NombreProcesador = "Intel Core i7"
                        },
                        new
                        {
                            IdProcesador = 3,
                            NombreProcesador = "AMD Ryzen 5"
                        },
                        new
                        {
                            IdProcesador = 4,
                            NombreProcesador = "Apple M1"
                        },
                        new
                        {
                            IdProcesador = 5,
                            NombreProcesador = "Apple M2"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Admin"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Normal"
                        });
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CorreoCorporativo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinContrato")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDimension")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdDimension");

                    b.HasIndex("IdRol");

                    b.HasIndex("Rut")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.UsuarioCuenta", b =>
                {
                    b.Property<int>("IdUsuarioCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioCuenta"));

                    b.Property<int>("IdCuenta")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioCuenta");

                    b.HasIndex("IdCuenta");

                    b.HasIndex("IdUsuario", "IdCuenta")
                        .IsUnique();

                    b.ToTable("UsuarioCuentas", (string)null);
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.ActivoFijo", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("IdDimension")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.DiscoDuro", "DiscoDuro")
                        .WithMany()
                        .HasForeignKey("IdDiscoDuro")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Audiomusica.Domain.Entities.EstadoActivo", "EstadoActivo")
                        .WithMany()
                        .HasForeignKey("IdEstadoActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("IdModelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.Procesador", "Procesador")
                        .WithMany()
                        .HasForeignKey("IdProcesador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Audiomusica.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dimension");

                    b.Navigation("DiscoDuro");

                    b.Navigation("EstadoActivo");

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("Procesador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Herramienta", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("IdDimension")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Dimension");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Modelo", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.MovimientoActivoFijo", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.ActivoFijo", "ActivoFijo")
                        .WithMany()
                        .HasForeignKey("IdActivoFijo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivoFijo");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.Dimension", "Dimension")
                        .WithMany()
                        .HasForeignKey("IdDimension")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dimension");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.UsuarioCuenta", b =>
                {
                    b.HasOne("Audiomusica.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("IdCuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Audiomusica.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioCuentas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Audiomusica.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioCuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
